[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Build environment variables
  NODE_ENV = "production"
  VITE_APP_NAME = "Code Recipe Book"
  VITE_APP_VERSION = "1.0.0"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://generativelanguage.googleapis.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variable documentation
# Set these in Netlify dashboard under Site settings > Environment variables:
# VITE_SUPABASE_URL = your_supabase_project_url
# VITE_SUPABASE_ANON_KEY = your_supabase_anon_key  
# VITE_GEMINI_API_KEY = your_gemini_api_key
